audio:
  duration: 5
  sample_rate: 16000
  channels: 1
  device: null
models:
  llama: models/llama-2-7b-chat.gguf
  voicevox_engine_path: '/Applications/VOICEVOX.app/Contents/MacOS/run'
  whisper: base
paths:
  logs: logs
  models: models
