animation:
  assets_dir: /Users/tmys-sasaki/Projects/Private/KaiwaChan/assets/images
  background_color:
  - 255
  - 255
  - 255
  default_character: default
  default_height: 400
  default_width: 300
  fps: 30
  window_height: 600
  window_width: 400
audio:
  channels: 1
  device: null
  duration: 5
  sample_rate: 16000
  silence_threshold: 0.03
behavior:
  auto_listen: true
  character:
    name: 会話ちゃん
    personality: 高貴な口調で、丁寧で優しく、時々ユーモアのある
    speaking_style: 簡潔で自然な日本語
logging:
  date_format: '%Y-%m-%d %H:%M:%S'
  format: '%(asctime)s [%(levelname)s] [%(name)s] %(message)s'
  level: 10
  max_files: 10
  max_size_mb: 5
models:
  current_engine: voicevox
  llm:
    max_tokens: 128
    n_batch: 512
    n_threads: 8
    path: /Users/tmys-sasaki/Projects/Private/KaiwaChan/models/ELYZA-japanese-Llama-2-7b-fast-instruct-q8_0.gguf
  parler:
    description: Emily voice is monotone yet slightly fast in delivery, with very
      clear audio and no background noise.
  voicevox:
    cache_enabled: true
    cache_size: 100
    engine_path: ''
    max_retries: 3
    retry_delay: 1.0
    speaker_id: 23
    timeout: 30
    url: http://localhost:50021
  whisper: base
paths:
  cache: /Users/tmys-sasaki/Projects/Private/KaiwaChan/cache
  logs: logs
  models: models
tts_engine:
  initialize_on_demand: true
voice_clone:
  chunk_size: 1024
  feature_dim: 256
  profiles_dir: /Users/tmys-sasaki/Projects/Private/KaiwaChan/profiles
  sample_rate: 22050
