audio:
  duration: 5
  sample_rate: 16000
  channels: 1
  device: null
models:
  llama:
    path: "models/granite-3.1-8b-instruct-Q4_K_M.gguf"
    n_threads: 8
    n_batch: 512
    max_tokens: 128
  voicevox:
    engine_path: '/Applications/VOICEVOX.app/Contents/MacOS/run'
    cache_size: 1000
    timeout: 5
  whisper: "base"
paths:
  logs: logs
  models: models
character:
  default_id: "default"
  models_dir: "models/live2d"
  expressions:
    - neutral
    - happy
    - sad
    - angry
    - surprised
  motions:
    - idle
    - talking
    - thinking
    - nodding
  window:
    width: 400
    height: 600
  fps: 30
  expressions:
    - neutral
    - happy
    - sad
    - mouth_open
    - mouth_closed
