audio:
  channels: 1
  device: null
  duration: 5
  sample_rate: 16000
  silence_threshold: 0.03
character:
  assets_dir: assets
  characters_dir: assets/images/characters
  default_id: default
  expressions:
  - neutral
  - happy
  - sad
  - mouth_open
  - mouth_closed
  fps: 30
  images_dir: assets/images
  models_dir: models/live2d
  motions:
  - idle
  - talking
  - thinking
  - nodding
  window:
    height: 600
    width: 400
logging:
  date_format: '%Y-%m-%d %H:%M:%S'
  format: '%(asctime)s [%(levelname)s] [%(name)s] %(message)s'
  level: 10
  max_files: 10
  max_size_mb: 5
models:
  current_engine: voicevox
  llm:
    file: granite-3.1-8b-instruct-Q4_K_M.gguf
    max_tokens: 128
    n_batch: 512
    n_threads: 8
  parler:
    description: A female speaker with a slightly high-pitched voice delivers her
      words at a moderate speed with a quite monotone tone in a confined environment,
      resulting in a quite clear audio recording
  voicevox:
    cache_size: 1000
    engine_path: /Applications/VOICEVOX.app/Contents/MacOS/run
    speaker_id: 60
    timeout: 5
  whisper: base
paths:
  assets: assets
  logs: logs
  models: models
voice_clone:
  chunk_size: 1024
  feature_dim: 256
  model_path: models/yourtts
  profiles_dir: profiles
  sample_rate: 16000
