audio:
  duration: 5
  sample_rate: 16000
  channels: 1
  device: null
  silence_threshold: 0.03
models:
  llm:
    file: "granite-3.1-8b-instruct-Q4_K_M.gguf"
    n_threads: 8
    n_batch: 512
    max_tokens: 128
  voicevox:
    engine_path: '/Applications/VOICEVOX.app/Contents/MacOS/run'
    cache_size: 1000
    timeout: 5
  whisper: "base"
paths:
  logs: logs
  models: models
  assets: assets
logging:
  level: 10  # DEBUG=10, INFO=20, WARNING=30, ERROR=40, CRITICAL=50
  format: '%(asctime)s [%(levelname)s] [%(name)s] %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'
  max_files: 10
  max_size_mb: 5
character:
  default_id: "default"
  models_dir: "models/live2d"
  assets_dir: "assets"  # アセットディレクトリのパス
  images_dir: "assets/images"  # 画像ディレクトリのパス
  characters_dir: "assets/images/characters"  # キャラクターディレクトリのパス
  expressions:
    - neutral
    - happy
    - sad
    - angry
    - surprised
    - blink
    - neutral_blink
  motions:
    - idle
    - talking
    - thinking
    - nodding
  window:
    width: 400
    height: 600
  fps: 30
  expressions:
    - neutral
    - happy
    - sad
    - mouth_open
    - mouth_closed
voice_clone:
  model_path: "models/yourtts"
  profiles_dir: "profiles"
  sample_rate: 16000
  chunk_size: 1024
  feature_dim: 256
